import { Montserrat } from "next/font/google";
import "./globals.css";
import ReduxProvider from "./reduxProvider";

const montserrat = Montserrat({
  subsets: ['latin'],
  display: 'swap',
})
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={montserrat.className}>
      <body>
        <ReduxProvider>
          {children}
        </ReduxProvider>
      </body>
    </html>
  );
}
