spring:
  datasource:
    url: ${URL_DB}
    username: ${USERNAME_DB}
    password: ${PASSWORD_DB}
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL95Dialect
    hibernate:
      ddl-auto: ${DDL_AUTO}
    show-sql: true

ACCESS_TOKEN_SECRET: ${ACCESS_TOKEN_SECRET}